### ISSUE TITLE
commit 80ba6f5b: Fix condition in handling data message 

### ISSUE THREAD

**Issue by showmen15** [project-capo/amber-java-clients#7]
Dlaczego taka zmiana ???? Teraz nie działa ???

Old:

    if (!message.hasAckNum() || message.getAckNum() == 0) 

New:

    if (message.hasAckNum() && message.getAckNum() != 0) {
    } else {

**Comment by paoolo** [comment]
Commit 80ba6f

**Comment by paoolo** [comment]
Zmiana była zła. Nie zauważyłem ``} else {``.

**Comment by pasuder** [comment]
Change in 8691fced. Available `jar` w f72d54eb
